import Modal from "@/components/Modal";
// import { Inter } from "next/font/google";
import "./globals.css";
import type { Metadata } from "next";
import { Providers } from "./Provider";
import styles from "../styles/Layout.module.css";
import { NextAuthProvider } from "./NextAuthProvider";
import { HiOutlineArrowLeft } from "react-icons/hi";
import { ToastContainer } from "react-toastify";
import Link from "next/link";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Trello Clone",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body suppressHydrationWarning={true}>
        <NextAuthProvider>
          <Providers attribute="class" defaultTheme="system" enableSystem>
            <main>{children}</main>
            <ToastContainer />
            <Modal />
          </Providers>
        </NextAuthProvider>
      </body>
    </html>
  );
}

export function Layout1({ children }: { children: React.ReactNode }) {
  return (
    <>
      <div className="flex h-screen bg-blue-400 dark:bg-gray-800">
        <div className="m-auto bg-slate-50 dark:bg-black/80 rounded-md w-3/5 h-[3/5] grid lg:grid-cols-2 ">
          <div className={styles.imgStyle}>
            <div className={styles.cartoonImg}></div>
            <div className={styles.cloud_1}></div>
            <div className={styles.cloud_2}></div>
          </div>
          <div className="relative right flex flex-col justify-evenly ">
            <div className=" text-center py-0 absolute left-[2%] top-[4px] w-10 h-9 text-violet-900">
              <Link href={"/"}>
                <HiOutlineArrowLeft className="w-10 h-9 dark:text-blue-500" />
              </Link>
            </div>
            <div className="text-center py-10">{children}</div>
          </div>
        </div>
      </div>
      <ToastContainer />
    </>
  );
}
